"""'pipeline_run_id' column to project

Revision ID: 25d2a58dc9ba
Revises: 44ca2b39be1c
Create Date: 2026-09-07 10:30:14.407259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d2a58dc9ba'
down_revision: Union[str, Sequence[str], None] = '44ca2b39be1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('pipeline_run_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'pipeline_run_id')
    # ### end Alembic commands ###
