"""add security report fields to project

Revision ID: 42a36d00e056
Revises: f68290801eb9
Create Date: 2026-08-26 09:24:16.350008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a36d00e056'
down_revision: Union[str, Sequence[str], None] = 'f68290801eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('severity_count', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('secret_count', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('last_secret', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'last_secret')
    op.drop_column('projects', 'secret_count')
    op.drop_column('projects', 'severity_count')
    # ### end Alembic commands ###
