"""ajout credentials db generes sur project_component

Revision ID: 9f9574a9d538
Revises: b9a50e61cefe
Create Date: 2026-08-28 08:22:49.668893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9574a9d538'
down_revision: Union[str, Sequence[str], None] = 'b9a50e61cefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_services', sa.Column('db_user', sa.String(), nullable=True))
    op.add_column('project_services', sa.Column('db_password', sa.String(), nullable=True))
    op.add_column('project_services', sa.Column('db_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_services', 'db_name')
    op.drop_column('project_services', 'db_password')
    op.drop_column('project_services', 'db_user')
    # ### end Alembic commands ###
