"""add deployment_runs history table and project relation

Revision ID: c8994bd7410b
Revises: e653d85936be
Create Date: 2026-09-09 09:29:58.174929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8994bd7410b'
down_revision: Union[str, Sequence[str], None] = 'e653d85936be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.Enum('MANUAL', 'WEBHOOK', name='deploymenttrigger'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLONING', 'BUILDING', 'SCANNING', 'DEPLOYING', 'SUCCESS', 'FAILED', name='pipelinestatus'), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_runs_id'), 'deployment_runs', ['id'], unique=False)
    op.create_index(op.f('ix_deployment_runs_project_id'), 'deployment_runs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_runs_project_id'), table_name='deployment_runs')
    op.drop_index(op.f('ix_deployment_runs_id'), table_name='deployment_runs')
    op.drop_table('deployment_runs')
    # ### end Alembic commands ###
