"""add vuln detail of deployement

Revision ID: f68290801eb9
Revises: ceaafa584db8
Create Date: 2026-08-25 08:18:32.975214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68290801eb9'
down_revision: Union[str, Sequence[str], None] = 'ceaafa584db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
        # 1. Créer le type ENUM PostgreSQL explicitement AVANT de l'utiliser
    fail_reason_enum = sa.Enum(
        'VULNERABILITY', 'SECRET_LEAK', 'BUILD_ERROR', 'CLONE_ERROR',
        'DETECTION_ERROR', 'DEPLOY_ERROR', 'OTHER',
        name='failreason'
    )
    fail_reason_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('fail_reason', fail_reason_enum, nullable=True))
    op.add_column('projects', sa.Column('vulnerabilities', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('critical_vuln_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'critical_vuln_count')
    op.drop_column('projects', 'vulnerabilities')
    op.drop_column('projects', 'fail_reason')
    # ### end Alembic commands ###
    # Supprimer le type ENUM à la fin
    fail_reason_enum = sa.Enum(name='failreason')
    fail_reason_enum.drop(op.get_bind(), checkfirst=True)