tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "secondary-container": "#e2e2e2",
                "error-container": "#ffdad6",
                "secondary-fixed": "#e2e2e2",
                "surface-container": "#e8eeff",
                "tertiary-fixed-dim": "#a0c9ff",
                "surface-dim": "#d0daf2",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f0f3ff",
                "background": "#f9f9ff",
                "primary-container": "#ff5c00",
                "on-secondary-fixed": "#1b1b1b",
                "surface-variant": "#d9e3fb",
                "on-tertiary": "#ffffff",
                "outline-variant": "#e4beb1",
                "outline": "#8f7065",
                "tertiary-fixed": "#d2e4ff",
                "on-primary-fixed": "#370e00",
                "on-secondary": "#ffffff",
                "on-primary-fixed-variant": "#802a00",
                "secondary-fixed-dim": "#c6c6c6",
                "secondary": "#5e5e5e",
                "inverse-primary": "#ffb59a",
                "surface": "#f9f9ff",
                "inverse-on-surface": "#ecf0ff",
                "on-secondary-fixed-variant": "#474747",
                "primary-fixed": "#ffdbce",
                "on-secondary-container": "#646464",
                "on-background": "#111c2d",
                "primary-fixed-dim": "#ffb59a",
                "on-surface-variant": "#5b4137",
                "surface-container-highest": "#d9e3fb",
                "surface-tint": "#a73a00",
                "error": "#ba1a1a",
                "surface-container-high": "#dfe8ff",
                "on-primary-container": "#521800",
                "primary": "#a73a00",
                "on-tertiary-container": "#002d51",
                "on-surface": "#111c2d",
                "on-primary": "#ffffff",
                "on-error-container": "#93000a",
                "on-error": "#ffffff",
                "on-tertiary-fixed": "#001c37",
                "tertiary": "#0061a6",
                "on-tertiary-fixed-variant": "#00497f",
                "inverse-surface": "#273143",
                "surface-bright": "#f9f9ff",
                "tertiary-container": "#0096fd"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "gutter": "24px",
                "sm": "8px",
                "margin-mobile": "16px",
                "margin-desktop": "32px",
                "lg": "24px",
                "md": "16px",
                "unit": "4px",
                "xxl": "80px",
                "xs": "4px",
                "max-width": "1280px",
                "xl": "40px"
            },
            "fontFamily": {
                "label-md": ["Inter"],
                "body-md": ["Inter"],
                "headline-lg": ["Inter"],
                "body-sm": ["Inter"],
                "mono-code": ["JetBrains Mono"],
                "headline-lg-mobile": ["Inter"],
                "headline-md": ["Inter"],
                "body-lg": ["Inter"],
                "display": ["Inter"],
                "label-sm": ["Inter"]
            },
            "fontSize": {
                "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "mono-code": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "display": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
            }
        }
    }
};
