tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "primary-fixed-dim": "#ffb59a",
              "on-tertiary-fixed-variant": "#00497f",
              "surface-dim": "#d0daf2",
              "surface-container": "#e8eeff",
              "on-primary-container": "#521800",
              "inverse-surface": "#273143",
              "on-primary": "#ffffff",
              "on-secondary-fixed": "#1b1b1b",
              "tertiary": "#0061a6",
              "tertiary-fixed": "#d2e4ff",
              "secondary": "#5e5e5e",
              "on-secondary-container": "#646464",
              "on-primary-fixed": "#370e00",
              "on-background": "#111c2d",
              "inverse-on-surface": "#ecf0ff",
              "surface-container-lowest": "#ffffff",
              "on-primary-fixed-variant": "#802a00",
              "primary-container": "#ff5c00",
              "surface-container-highest": "#d9e3fb",
              "error": "#ba1a1a",
              "on-surface": "#111c2d",
              "surface": "#f9f9ff",
              "outline-variant": "#e4beb1",
              "surface-variant": "#d9e3fb",
              "secondary-container": "#e2e2e2",
              "error-container": "#ffdad6",
              "surface-container-low": "#f0f3ff",
              "on-error": "#ffffff",
              "inverse-primary": "#ffb59a",
              "primary-fixed": "#ffdbce",
              "on-error-container": "#93000a",
              "outline": "#8f7065",
              "on-tertiary-fixed": "#001c37",
              "surface-bright": "#f9f9ff",
              "tertiary-fixed-dim": "#a0c9ff",
              "on-tertiary": "#ffffff",
              "background": "#f9f9ff",
              "on-surface-variant": "#5b4137",
              "on-tertiary-container": "#002d51",
              "on-secondary": "#ffffff",
              "secondary-fixed-dim": "#c6c6c6",
              "primary": "#a73a00",
              "surface-tint": "#a73a00",
              "on-secondary-fixed-variant": "#474747",
              "secondary-fixed": "#e2e2e2",
              "surface-container-high": "#dfe8ff",
              "tertiary-container": "#0096fd"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "max-width": "1280px",
              "xxl": "80px",
              "md": "16px",
              "margin-mobile": "16px",
              "margin-desktop": "32px",
              "xl": "40px",
              "unit": "4px",
              "sm": "8px",
              "gutter": "24px",
              "lg": "24px",
              "xs": "4px"
      },
      "fontFamily": {
              "headline-md": ["Inter"],
              "body-sm": ["Inter"],
              "headline-lg": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "label-md": ["Inter"],
              "body-md": ["Inter"],
              "mono-code": ["JetBrains Mono"],
              "display": ["Inter"],
              "body-lg": ["Inter"],
              "label-sm": ["Inter"]
      },
      "fontSize": {
              "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "mono-code": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "display": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
}
